### ISSUE TITLE
Security vulnerability in debug package

### ISSUE THREAD

**Issue by ayafor** [bjrmatos/read-xml#2]
Hi,

The used version of debug package has a vulnerability: https://nodesecurity.io/advisories/534

Could it be upgraded?

**Comment by bjrmatos** [comment]
yes! i will update it in the weekend but i can also accept a PR from you i want to do it first.

**Comment by ayafor** [comment]
Ok, thanks.

I submitted a pull request

**Comment by bjrmatos** [comment]
done in `3.0.0`. thanks!
